// <auto-generated />
namespace MountainTourismApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ert7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ert7));
        
        string IMigrationMetadata.Id
        {
            get { return "202110020838480_ert7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
